### ISSUE TITLE
Button test fails

### ISSUE THREAD

**Issue by DeluxZ** [hamatoyogi/react-tw-blog-post#1]
I really like your blog post so far but running into an 'issue'.

At the point you are going to test the button it fails with a typescript error and you extend the `Button` with the `ButtonHTMLAttributes`. When you continue in the blog post you state you are testing option 2 of the button (applying the styles with option 2) but when I look in your code it's option 1. If I try it with option 2 I get an error `No overload matches this call`.

Button.tsx
```Button.tsx
import React, { FC, ButtonHTMLAttributes } from 'react';
import styled from 'styled-components';

const StyledButton = styled.button.attrs(() => ({
  className: `px-8 py-2 font-semibold text-white transition duration-500 ease-in-out transform rounded-lg shadow-xl bg-gradient-to-r from-red-300 to-blue-300 hover:from-pink-400 hover:to-indigo-400`,
}))<{ variant: ButtonVariants }>`
  color: ${({ variant }) => (variant === 'warning' ? 'red' : '')};
`;

type ButtonVariants = 'default' | 'warning';
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  text: string;
  variant?: ButtonVariants;
}

export const Button: FC<ButtonProps> = ({
  text,
  variant = 'default',
  ...rest
}) => {
  return (
    <StyledButton variant={variant} {...rest}>
      {text}
    </StyledButton>
  );
};
```

**Comment by hamatoyogi** [comment]
@DeluxZ Glad you liked the post!

The issue that you are running into is a TS issue. Basically, what is missing here is "telling" styled-components `attrs` function what is being passed into it. If you look closely at the TS error you will see the issue:
![image](https://user-images.githubusercontent.com/6682981/108953291-a36bce00-7673-11eb-9fcf-9f02a16e95cb.png)

To fix the issue,  all you need to do is get the `className` property out of the `attrs` and pass it on into the "enhanced" `className` (so you're able to pass more classNames into `StyledButton` if you need to. This is how it should look like:
```typescript
import React, { FC, ButtonHTMLAttributes } from 'react';
import styled from 'styled-components';

const StyledButton = styled.button.attrs(({ className }) => ({
  className: `${className} px-8 py-2 font-semibold text-white transition duration-500 ease-in-out transform rounded-lg shadow-xl bg-gradient-to-r from-red-300 to-blue-300 hover:from-pink-400 hover:to-indigo-400`,
}))<{ variant: ButtonVariants }>`
  color: ${({ variant }) => (variant === 'warning' ? 'red' : '')};
`;

type ButtonVariants = 'default' | 'warning';
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  text: string;
  variant?: ButtonVariants;
}

export const Button: FC<ButtonProps> = ({
  text,
  variant = 'default',
  ...rest
}) => {
  return (
    <StyledButton variant={variant} {...rest}>
      {text}
    </StyledButton>
  );
};
```

Hope that helps! :-)
